### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by pushrax** [revel/meta#1]

**Comment by brendensoares** [comment]
@pushrax [I'm not exactly sure yet](https://github.com/revel/revel/issues/875)

**Comment by pedromorgan** [comment]
This is going to be used on the next gen revel-www website.

it will contain some YAML and git submodules to generate different "versions" of the documentation etc..

Will be onto this soon (need time as usual)

**Comment by brendensoares** [comment]
@pedromorgan please add a `README.md` to this repo with your plans. Thanks!
